version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAVA_VERSION: ${JAVA_VERSION:-17}
        MAVEN_VERSION: ${MAVEN_VERSION:-3.9.6}
        __SECURITY_ARGS__

    volumes:
      - ..:/workspace:cached

    command: sleep infinity

    network_mode: host
