version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.12}
        __SECURITY_ARGS__

    volumes:
      - ..:/workspace:cached

    command: sleep infinity

    __NETWORK_MODE__
    __NETWORKS_SERVICE__
__NETWORKS_TOP__
