version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:-8.3}
        __SECURITY_ARGS__

    volumes:
      - ..:/workspace:cached

    command: sleep infinity

    __NETWORK_MODE__
