version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RUST_TOOLCHAIN: ${RUST_TOOLCHAIN:-stable}
        __SECURITY_ARGS__

    volumes:
      - ..:/workspace:cached

    command: sleep infinity

    network_mode: host
