version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: devdb
      MYSQL_USER: developer
      MYSQL_PASSWORD: developer
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

    __NETWORKS_SERVICE__

volumes:
  db_data:

__NETWORKS_TOP__
