version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: ${NODE_VARIANT:-22-bullseye}
        NODE_MAJOR_VERSION: ${NODE_MAJOR_VERSION:-22}
        __SECURITY_ARGS__

    volumes:
      - ..:/workspace:cached

    command: sleep infinity

    __NETWORK_MODE__
